language: php
php:
    - '7.1'
env:
    - TRAVIS_NODE_VERSION="7"
cache:
    directories:
        - $HOME/.yarn-cache

before_install:
    - composer self-update
    # Update nodejs
    - rm -rf ~/.nvm
    - git clone https://github.com/creationix/nvm.git ~/.nvm
    - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
    - source ~/.nvm/nvm.sh
    - nvm install $TRAVIS_NODE_VERSION
    - node --version
    # Yarn
    - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -yqq yarn
    - yarn --version
    # Tools for building frontend
    - gem install sass
    - gem install compass
before_script:
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - composer install --prefer-source --no-interaction
    - yarn
    - node_modules/.bin/bower install
    - composer build
script:
    - composer test-all
